version: '3.1'

services:
  db:
    image: postgres
    container_name: planning-poker-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: planning_poker_db
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
